devices/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^update/$', views.update, name='update'),
    url(r'^new/$', views.new, name='new'),
    url(r'^(?P<room_id>[0-9]+)/manage/$', views.manage, name='manage'),
    url(r'^(?P<room_id>[0-9]+)/remove_device/(?P<device_id>[0-9]+)$', views.remove_device, name='remove_device'),
    url(r'^(?P<function_id>[0-9]+)/send_function/$', views.send_function, name='send_function'),
]

hubs/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^manage/$', views.manage, name='manage'),
    url(r'^change_name/$', views.change_name, name='change_name'),
    url(r'^change_room/$', views.change_room, name='change_room'),
    url(r'^(?P<hub_id>[0-9]+)/remove_hub/$', views.remove_hub, name='remove_hub'),
]

iriot/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls', namespace="accounts")),
    url(r'^rooms/', include('rooms.urls', namespace="rooms")),
    url(r'^hubs/', include('hubs.urls', namespace="hubs")),
    url(r'^devices/', include('devices.urls', namespace="devices")),
    url(r'^', include('master.urls', namespace="master")),
]

devices/models.py
from __future__ import unicode_literals

from django.db import models
from rooms.models import Room

# Create your models here.

class Device(models.Model):
    name = models.CharField(max_length=30)
    room = models.ForeignKey(Room)

class Function(models.Model):
    function = models.CharField(max_length=30)
    prontohex = models.CharField(max_length=2000)
    sendhex = models.CharField(max_length=2000)
    device = models.ForeignKey(Device)

devices/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib import messages
from .models import Device, Function
from rooms.models import Room
import boto3
import json
import re
from random import randint

# Create your views here.
@login_required
def new(request):
    d = Device()
    d.name = request.POST['name']
    d.room = Room.objects.get(id=request.POST['room_id'])
    d.save()
    for key in request.POST.keys():
        if key[:2] == 'nf':
            make_function(request, request.POST["nf"+key[2:]],request.POST["np"+key[2:]],-1,d)

    return HttpResponseRedirect('/devices/'+request.POST['room_id']+'/manage')

@login_required
def update(request):
    dev = Device.objects.get(id=request.POST['device_id'])
    if dev.room.owner != request.user:
        messages.warning(request, "You can't update a device you dont own!")
        return HttpResponseRedirect('/devices/'+request.POST['room_id']+'/manage')
    dev.name = request.POST['q']
    dev.save()

    #modify existing fields
    for key in request.POST.keys():
        if key[0] == 'f':
            make_function(request, request.POST["f"+key[1:]],request.POST["p"+key[1:]],key[1:])
        if key[:2] == 'nf':
            make_function(request, request.POST["nf"+key[2:]],request.POST["np"+key[2:]],-1,dev)

    return HttpResponseRedirect('/devices/'+request.POST['room_id']+'/manage')

@login_required
def make_function(request, name, code, existing_id, d=None):
    f = Function()
    if existing_id != -1:
        f = Function.objects.get(id=existing_id)
    f.function = name
    hexstring = code.replace("0x","").replace(" ","").replace(",","").upper()
    if re.match("^[0-9A-F]+$", hexstring) and len(hexstring) % 4 == 0:
        hexarray = [hexstring[i:i+4] for i in range(0, len(hexstring), 4)]
        f.prontohex = " ".join(hexarray)
        unique_numbers = []
        letter_string = ""
        for s in hexarray:
            number = str(int(s, 16))
            if number not in unique_numbers:
                unique_numbers.append(number)
            letter_string += chr(ord('a') + unique_numbers.index(number))
        f.sendhex = str(len(unique_numbers)) + "," + ",".join(unique_numbers) + "," + letter_string

        if existing_id == -1:
            f.device = d
        f.save()
    else:
        messages.warning(request, "ProntoHex code invalid for " + name)
        if existing_id == -1:
            for code in d.function_set.all():
                code.delete()
            d.delete()
        return HttpResponseRedirect('/devices/'+request.POST['room_id']+'/manage')


@login_required
def manage(request, room_id):
    if Room.objects.get(id=room_id).owner != request.user:
        messages.warning(request, "You can't manage a device you dont own.")
        return HttpResponseRedirect("/")
    name = Room.objects.get(id=room_id).name
    return render(request, 'devices/manage.html', {'roomDevices': Device.objects.filter(room__id=room_id), 'roomID': room_id, 'roomName': name})

@login_required
def remove_device(request, device_id, room_id):
    dev = Device.objects.get(id=device_id)
    if dev.room.owner != request.user:
        messages.warning(request, "Your device was not removed.")
        return HttpResponseRedirect('/devices/'+str(room_id)+'/manage')
    #delete all prontohex codes associated with device
    for code in dev.function_set.all():
        code.delete()
    dev.delete()
    return HttpResponseRedirect('/devices/'+str(room_id)+'/manage')

@login_required
def send_function(request, function_id):
    client = boto3.client('iot-data', region_name='us-east-1')
    func = Function.objects.get(id=function_id)
    payload = {"state":{"desired":{"p": func.sendhex+"?"+str(randint(1,99))}}}
    if func.device.room.owner != request.user:
        HttpResponse("f")
    try:
        for hub in func.device.room.hub_set.all():
            client.update_thing_shadow(thingName=hub.serial_number,payload=json.dumps(payload))
    except:
        return HttpResponse("f")
    return HttpResponse("t")

devices/templates/devices/manage.html
{% extends "master/base.html" %}
{% block body_block %}
<div class="panel panel-default">
<div class="panel-heading">
<h3 class="panel-title pull-left" style="padding-top: 7.5px;">Devices for {{roomName}}</h3>
<a class="btn btn-default pull-right btn-sm" data-toggle="modal" data-target="#newModal"><i class="glyphicon glyphicon-plus"></i></a>
<div class="clearfix"></div>
</div>
<table class="table">
  <tr>
    <th>Name</th>
    <th>Functions</th>
    <th>Actions</th>
  </tr>
  {% for device in roomDevices %}
  <tr>
    <td> {{ device.name }} </td>
    <td>
      <button type="button" class="btn btn-link" data-toggle="collapse" data-target="#view{{device.id}}">View functions</button>
      <div id="view{{device.id}}" class="collapse">
        <table class="table">
          {% for function in device.function_set.all %}
          <tr>
            <td>{{function.function}}</td>
            <td><code>{{function.prontohex}}</code></td>
          </tr>
          {% endfor %}
        </table>
      </div>
    </td>
    <td>
      <a data-toggle="modal" data-target="#modal{{device.id}}">Edit</a>
      <a href="{% url "devices:remove_device" roomID device.id %}">Delete</a>
    </td>
  </tr>
  {% endfor %}
</table>
</div>

{% for device in roomDevices %}
<div class="modal fade" id="modal{{device.id}}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Edit Device</h4>
      </div>
      <form method="post" action="{% url 'devices:update' %}">
      {% csrf_token %}
      <div class="modal-body">
        <input type="text" class="form-control" name="q" value="{{device.name}}"/>
        <input type="hidden" name="device_id" value="{{ device.id }}">
        <input type="hidden" name="room_id" value="{{ roomID }}">
        <br />
        <table class="table" id="t{{device.id}}">
          <tr>
            <th>Name</th>
            <th>ProntoHex code</th>
          </tr>
          {% for function in device.function_set.all %}
          <tr>
            <td><input type="text" class="form-control" name="f{{function.id}}" value="{{function.function}}"/></td>
            <td><input type="text" class="form-control" name="p{{function.id}}" value="{{function.prontohex}}"/></td>
            <td> </td>
          </tr>
          {% endfor %}
        </table>
      <br />
      <button type="button" class="btn btn-default btn-small" onclick="addField('#t{{device.id}}')">Add Function</button>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Save changes</button>
      </div>
      </form>
    </div>
  </div>
</div>
{% endfor %}

<div class="modal fade" id="newModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">New Device</h4>
      </div>
      <form method="post" action="{% url 'devices:new' %}">
      {% csrf_token %}
      <div class="modal-body">
        <input type="text" class="form-control" name="name" placeholder="Device Name"/>
        <input type="hidden" name="room_id" value="{{ roomID }}">
        <br />
        <table class="table" id="tnew">
          <tr>
            <th>Name</th>
            <th>ProntoHex code</th>
          </tr>
        </table>
      <br />
        <button type="button" class="btn btn-default btn-small" onclick="addField('#tnew')">Add Function</button>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Save changes</button>
      </div>
      </form>
    </div>
  </div>
</div>

{% endblock %}
{% block head_block %}
<script type="text/javascript">
var c = 0;
function addField(sel){
  var text = "<tr id='new"+c+"'><td><input type='text' class='form-control' name='nf"+c+"'/></td><td><input type='text' class='form-control' name='np"+c+"'/></td><td><a class='btn btn-danger' onclick='removeField("+c+")''><i class='glyphicon glyphicon-remove'></i></a></td></tr>";
  $(text).appendTo(sel);
  c++;
}
function removeField(n){
  var rowSel = "#new"+n;
  var obj = $(rowSel);
  obj.remove();
}
</script>
{% endblock %}