hubs/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^manage/$', views.manage, name='manage'),
    url(r'^change_name/$', views.change_name, name='change_name'),
    url(r'^change_room/$', views.change_room, name='change_room'),
    url(r'^(?P<hub_id>[0-9]+)/remove_hub/$', views.remove_hub, name='remove_hub'),
]

iriot/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls', namespace="accounts")),
    url(r'^rooms/', include('rooms.urls', namespace="rooms")),
    url(r'^hubs/', include('hubs.urls', namespace="hubs")),
    url(r'^devices/', include('devices.urls', namespace="devices")),
    url(r'^', include('master.urls', namespace="master")),
]

hubs/models.py
from __future__ import unicode_literals

from django.db import models
from rooms.models import Room
from django.contrib.auth.models import User
import boto3
import botocore

# Create your models here.
class Hub(models.Model):
    alias = models.CharField(max_length=30)
    owner = models.ForeignKey(User)
    room = models.ForeignKey(Room, blank=True, null=True)
    serial_number = models.CharField(max_length=30, unique=True)
    def is_updated(self):
        client = boto3.client('iot-data', region_name='us-east-1')
        response = client.get_thing_shadow(thingName=self.serial_number)
        return "\"delta\":" not in response['payload'].read()

rooms/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Room(models.Model):
    name = models.CharField(max_length=30)
    owner = models.ForeignKey(User)

hubs/forms.py
from django import forms
from .models import Hub

class HubForm(forms.ModelForm):
    alias = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    serial_number = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    class Meta:
        model = Hub
        fields = ('alias','serial_number')

hubs/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib import messages
from .models import Hub
from rooms.models import Room
from .forms import HubForm
import boto3
import botocore

# Create your views here.
@login_required
def manage(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        client = boto3.client('iot', region_name='us-east-1')
        # create a form instance and populate it with data from the request:
        f = HubForm(request.POST)
        # check whether it's valid:
        if f.is_valid():
            # Save the form data to the database.
            # But dont yet commit, we still have some data to add.
            hub = f.save(commit=False)
            isTaken = True
            try:
                isTaken = client.describe_thing(thingName=hub.serial_number)['attributes']['taken'] == 'true'
            except botocore.exceptions.ClientError:
                messages.warning(request, 'There is no device with that serial number!')
                return render(request, 'hubs/manage.html', {'hub_form': f})
            except:
                messages.warning(request, 'Error communicating with device!')
                return render(request, 'hubs/manage.html', {'hub_form': f})
            if isTaken:
                messages.warning(request, 'Hub Already Registered!')
                return render(request, 'hubs/manage.html', {'hub_form': f})

            hub.owner = request.user

            client.update_thing(thingName=hub.serial_number,attributePayload={'attributes': {'taken': 'true'},'merge': True})

            # NOW we can save
            hub.save();




            # redirect to a new URL:
            return HttpResponseRedirect('/hubs/manage')
        else:
            messages.warning(request, "There were some errors in your request. Try Again!")
            return render(request, 'hubs/manage.html', {'hub_form': f})
    # if a GET (or any other method) we'll create a blank form
    else:
        hub_form = HubForm()
        return render(request, 'hubs/manage.html', {'hub_form': hub_form})

    return render(request, 'hubs/master.html')

@login_required
def remove_hub(request, hub_id):
    client = boto3.client('iot', region_name='us-east-1')
    hub = Hub.objects.get(id=hub_id)
    if hub.owner == request.user:
        try:
            client.update_thing(thingName=hub.serial_number,attributePayload={'attributes': {'taken': 'false'},'merge': True})
        except:
            messages.warning(request, "Hub could not be removed. Communication with device failed.")
            return HttpResponseRedirect('/hubs/manage')

        hub.delete()
    else:
        messages.warning(request, "Your hub was not deleted.")
    return HttpResponseRedirect('/hubs/manage')

@login_required
def change_name(request):
    item = Hub.objects.get(id=request.POST["hub_id"])
    if item.owner == request.user:
        item.alias = request.POST['q']
        item.save()
    else:
        messages.warning(request, 'Name not changed!')
    return HttpResponseRedirect('/hubs/manage')

@login_required
def change_room(request):
    item = Hub.objects.get(id=request.POST["hub_id"])
    room = Room.objects.get(id=request.POST["room_val"])
    if item.owner == request.user:
        item.room = room
        item.save()
    else:
        messages.warning(request, 'Name not changed!')
    return HttpResponseRedirect('/hubs/manage')

hubs/templates/hubs/manage.html
{% extends "master/base.html" %}
{% block body_block %}
<div class="panel panel-default">
<div class="panel-heading">
  <h3 class="panel-title pull-left" style="padding-top: 7.5px;">My Hubs</h3>
  <a class="btn btn-default pull-right btn-sm" data-toggle="modal" data-target="#newModal"><i class="glyphicon glyphicon-plus"></i></a>
<div class="clearfix"></div>
</div>
<table class="table">
  <tr>
    <th>Alias</th>
    <th>Status</th>
    <th>Serial Number</th>
    <th>Room</th>
    <th>Actions</th>
  </tr>
  {% for hub in user.hub_set.all %}
  <tr>
    <td> {{ hub.alias }} </td>
    <td>
      {% if hub.is_updated %}
      <span class="label label-success">Updated</span>
      {% else %}
      <span class="label label-danger">Out Of Date</span>
      {% endif %}
    </td>
    <td>{{ hub.serial_number }}</td>
    <td>
      <form id="move{{hub.id}}" method="post" action="{% url 'hubs:change_room' %}">
      {% csrf_token %}
        <select name="room_val" onChange = "$('#move{{hub.id}}').submit()">
          <option value="-1"></option>
          {% for room in user.room_set.all %}
          <option value="{{room.id}}" {%if room.name == hub.room.name %} selected="selected" {% endif %}>{{ room.name }}</option>
          {% endfor %}
            <input type="hidden" name="hub_id" value="{{ hub.id }}">
        </select>
        </form>
    </td>
    <td>
      <a data-toggle="modal" data-target="#modal{{hub.id}}">Edit</a>
      <a href="{% url "hubs:remove_hub" hub.id %}">Delete</a>
    </td>
  </tr>
  {% endfor %}
</table>
</div>

{% for hub in user.hub_set.all %}
<div class="modal fade" id="modal{{hub.id}}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Edit Name</h4>
      </div>
      <form method="post" action="{% url 'hubs:change_name' %}">
      {% csrf_token %}
      <div class="modal-body">
        <input type="text" class="form-control" name="q" value="{{hub.alias}}"/>
        <input type="hidden" name="hub_id" value="{{ hub.id }}">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Save changes</button>
      </div>
      </form>
    </div>
  </div>
</div>
{% endfor %}

<div class="modal fade" id="newModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">New Hub</h4>
      </div>
      <form method="post" action="{% url 'hubs:manage' %}">
      <div class="modal-body">
        {% csrf_token %}

        {% for field in hub_form.visible_fields %}
        <div class="form-group">
          {{ field.errors }}
          <label>{{ field.label }}</label>
          {{ field }}
        </div>
        {% endfor %}
        <br/>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Add Hub</button>
      </div>
    </form>
    </div>
  </div>
</div>

{% endblock %}