accounts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
]

hubs/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^manage/$', views.manage, name='manage'),
    url(r'^change_name/$', views.change_name, name='change_name'),
    url(r'^change_room/$', views.change_room, name='change_room'),
    url(r'^(?P<hub_id>[0-9]+)/remove_hub/$', views.remove_hub, name='remove_hub'),
]

iriot/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls', namespace="accounts")),
    url(r'^rooms/', include('rooms.urls', namespace="rooms")),
    url(r'^hubs/', include('hubs.urls', namespace="hubs")),
    url(r'^devices/', include('devices.urls', namespace="devices")),
    url(r'^', include('master.urls', namespace="master")),
]

master/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^about/$', views.about, name='about'),

]

accounts/models.py
from django.db import models

# Create your models here.

from django.contrib.auth.models import User

accounts/forms.py
from django import forms
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control'}))
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    email = forms.EmailField(widget=forms.TextInput(attrs={'class':'form-control'}))
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password')

accounts/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from .forms import UserForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User

def register(request):

    # A boolean value for telling the template whether the registration was successful.
    # Set to False initially. Code changes value to True when registration succeeds.
    registered = False

    # If it's a HTTP POST, we're interested in processing form data.
    if request.method == 'POST':
        # Attempt to grab information from the raw form information.
        # Note that we make use of both UserForm and UserProfileForm.
        user_form = UserForm(data=request.POST)

        # If the two forms are valid...
        if user_form.is_valid():
            # Save the user's form data to the database.
            user = user_form.save()

            # Now we hash the password with the set_password method.
            # Once hashed, we can update the user object.
            user.set_password(user.password)

            user.save()

            registered = True

        # Invalid form or forms - mistakes or something else?
        # Print problems to the terminal.
        # They'll also be shown to the user.
        else:
            print(user_form.errors)

    # Not a HTTP POST, so we render our form using two ModelForm instances.
    # These forms will be blank, ready for user input.
    else:
        user_form = UserForm()

    # Render the template depending on the context.
    return render(request, 'accounts/register.html', {'user_form': user_form, 'registered': registered} )

def user_login(request):

    # If the request is a HTTP POST, try to pull out the relevant information.
    if request.method == 'POST':
        # Gather the username and password provided by the user.
        # This information is obtained from the login form.
                # We use request.POST.get('<variable>') as opposed to request.POST['<variable>'],
                # because the request.POST.get('<variable>') returns None, if the value does not exist,
                # while the request.POST['<variable>'] will raise key error exception
        username = request.POST.get('username')
        password = request.POST.get('password')

        # Use Django's machinery to attempt to see if the username/password
        # combination is valid - a User object is returned if it is.
        user = authenticate(username=username, password=password)

        # If we have a User object, the details are correct.
        # If None (Python's way of representing the absence of a value), no user
        # with matching credentials was found.
        if user:
            # Is the account active? It could have been disabled.
            if user.is_active:
                # If the account is valid and active, we can log the user in.
                # We'll send the user back to the homepage.
                login(request, user)
                return HttpResponseRedirect('/')
            else:
                # An inactive account was used - no logging in!
                messages.warning(request, 'Your account is disabled. Please contact support.')
                return HttpResponseRedirect('/')
        else:
            # Bad login details were provided. So we can't log the user in.
            # TODO: USE FLASH MESSAGES -----------------
            messages.warning(request, 'Invalid Login.')
            return HttpResponseRedirect(reverse('accounts:login'))

    # The request is not a HTTP POST, so display the login form.
    # This scenario would most likely be a HTTP GET.
    else:
        # No context variables to pass to the template system, hence the
        # blank dictionary object...
        return render(request, 'accounts/login.html', {})


# Use the login_required() decorator to ensure only those logged in can access the view.
@login_required
def user_logout(request):
    # Since we know the user is logged in, we can now just log them out.
    logout(request)
    messages.success(request, 'You are now logged out.')
    return HttpResponseRedirect('/')

accounts/templates/accounts/login.html
{% extends "master/base.html" %}
{% block body_block %}
        <h1>Login</h1>

        <form id="login_form" method="post" action="/accounts/login/">
            {% csrf_token %}
            <label for="username">Username</label>
            <input class="form-control" type="text" name="username" value="" size="50" />
            <br />
            <label for="password">Password</label>
            <input class="form-control" type="password" name="password" value="" size="50" />
            <br />

            <input type="submit" value="submit" class="btn btn-default" />
        </form>
{% endblock %}

accounts/templates/accounts/register.html
{% extends "master/base.html" %}
{% block body_block %}
        <h1>Register</h1>

        {% if registered %}
        <H2>You are Registered. <a href="{% url 'master:index' %}">Continue to Home Page.</a></H2>
        {% else %}

        <form id="user_form" method="post" action="/accounts/register/" enctype="multipart/form-data">

            {% csrf_token %}

            <!-- Display each form. The as_p method wraps each element in a paragraph
                 (<p>) element. This ensures each element appears on a new line,
                 making everything look neater. -->
            {% for field in user_form.visible_fields %}
            <div class="form-group">
            {{ field.errors }}
            <label>{{ field.label }}</label>
            {{ field }}
            </div>
            {% endfor %}

            <!-- Provide a button to click to submit the form. -->
            <input class="btn btn-primary" type="submit" name="submit" value="Register" />
        </form>
        {% endif %}
{% endblock %}