accounts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
]

hubs/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^manage/$', views.manage, name='manage'),
    url(r'^change_name/$', views.change_name, name='change_name'),
    url(r'^change_room/$', views.change_room, name='change_room'),
    url(r'^(?P<hub_id>[0-9]+)/remove_hub/$', views.remove_hub, name='remove_hub'),
]

iriot/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls', namespace="accounts")),
    url(r'^rooms/', include('rooms.urls', namespace="rooms")),
    url(r'^hubs/', include('hubs.urls', namespace="hubs")),
    url(r'^devices/', include('devices.urls', namespace="devices")),
    url(r'^', include('master.urls', namespace="master")),
]

master/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^about/$', views.about, name='about'),

]

rooms/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^add_edit_room/$', views.room, name='room'),
    url(r'^(?P<room_id>[0-9]+)/remove_room/$', views.remove_room, name='remove_room'),
    url(r'^edit_room_name/$', views.edit_room_name, name='edit_room_name'),
]

devices/models.py
from __future__ import unicode_literals

from django.db import models
from rooms.models import Room

# Create your models here.

class Device(models.Model):
    name = models.CharField(max_length=30)
    room = models.ForeignKey(Room)

class Function(models.Model):
    function = models.CharField(max_length=30)
    prontohex = models.CharField(max_length=2000)
    sendhex = models.CharField(max_length=2000)
    device = models.ForeignKey(Device)

master/models.py
from django.db import models

# Create your models here.

rooms/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Room(models.Model):
    name = models.CharField(max_length=30)
    owner = models.ForeignKey(User)

master/views.py
from django.shortcuts import render
from rooms.forms import RoomForm

# Create your views here.

def index(request):
    return render(request, 'master/index.html', {'room_form': RoomForm()})

def about(request):
    return render(request, 'master/about.html', {})

master/templates/master/about.html
{% extends "master/base.html" %}
{% block body_block %}
<h1>About <i>i</i>Riot.</h1>
<h3>The Internet of Things has been reinvented.</h3>
<div class="col-lg-12">
<div class="col-lg-4"><img class="img-responsive" src="https://s3.amazonaws.com/iriot/flow.JPG"></div>
<p>In terms of existing products, <i>i</i>Riot is a mix between a traditional Internet of Things (IoT) appliance and a universal remote. It acts as an Internet-connected delegate to Infrared (IR) devices through acting as a universal remote to these devices. IR is the industry standard communications medium for remote control. The standard of IR communication is a 940 nanometer wavelength of light, which is invisible to the human eye, but can be seen by some cameras and some special IR sensors in all IR enabled devices. IR sensors are designed to produce a voltage if the incoming light is a 38 kHz pulse width modulated signal. Therefore, a “1” can be sent to the sensor by sending a 38 kHz square wave, and a “0” can be sent by sending no light. Our project will take advantage of this simple protocol and merge it with the world of IoT to achieve simple but effective home control.</p>
<p>We all want to have easy control over our homes without spending the time and money necessary to build a totally integrated smart home. Companies such as Alarm.com have tried with some success to enter the smart home market, but its products are expensive to purchase and maintain. Instead of making our own line of smart components such as Internet connected thermostats and TVs, we recognize that many devices we want to control can already be controlled through IR as they are with a universal remote. Devices such as entertainment equipment, some light switches, motorized window blinds, and air conditioning units already have this capability, and can be bought at a lower cost than their Wi-Fi enabled counterparts.</p>
<p>Our project also solves some security vulnerabilities generally associated with IoT technologies as well. Existing IoT solutions have smart home components which directly connect to the institutional or residential wireless Internet connection. However, connecting every light switch in a building to the wireless network and to the Internet provides additional points of entry for cyber-attacks and puts pressure on the network. Through <i>i</i>Riot, we will reduce the number of connected devices in the home, and therefore reduce the attack surface. In addition, we will communicate with the device over SSL using unique encryption keys for every device. In the world of IoT, manufacturers have little interest in security to keep the form and cost of its device to a minimum, but we will take security seriously.</p>
<p>The bulk of the project is an Internet-connected dome which serves as an IR blaster to control existing IR controlled products. The dome will contain an Internet-connected microcontroller (the Texas Instruments CC3200) at its core. It will interface via the MQ Telemetry Transport (MQTT) protocol, a commonly used IoT push protocol, with the Amazon Web Services (AWS) IoT service. Users may login to a web app built using the Python Django Web Framework to manage hubs and control devices. The web app will interface with AWS IoT though a REST API, and pass basic information such as the IR code and the transmitting hub. AWS IoT maintains the MQTT connection with all the hubs, and pushes the IR code to the desired hubs. The hub receives and interprets the IR code and broadcasts the desired command to an IR enabled device to fulfill a task (i.e. turning off the lights or opening the blinds). The system can control any IR device within Line of Sight (LoS) of the dome.</p>
</div>
{% endblock %}

master/templates/master/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="HandheldFriendly" content="true">
    <title>iRiot | {% block title %}This page{% endblock %}</title>

    <!--<link href="https://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">-->
    <link href="https://s3.amazonaws.com/iriot/bootstrap.min.css" rel="stylesheet">
    <link href="https://getbootstrap.com/examples/dashboard/dashboard.css" rel="stylesheet">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="https://getbootstrap.com/dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="https://getbootstrap.com/assets/js/ie10-viewport-bug-workaround.js"></script>

    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

  {% block head_block %}{% endblock %}
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/"><i>i</i>Riot</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
                <li><a href="/">Home</a></li>
                <li><a href="{% url 'master:about' %}">About</a></li>
                    {% if user.is_authenticated %}
                        <li><a href="{% url 'accounts:logout' %}">Logout <i class="glyphicon glyphicon-log-out"></i></a></li>
                    {% else %}
                        <li><a href="{% url 'accounts:register' %}">Register</a></li>
                        <li><a href="{% url 'accounts:login' %}">Login <i class="glyphicon glyphicon-log-in"></i></a></li>
                    {% endif %}
              </ul>
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          {% if not user.is_authenticated %}
          <form id="login_form" method="post" action="/accounts/login/">
            {% csrf_token %}
            <label for="username">Username</label>
            <input class="form-control" type="text" name="username" value="" size="50" />
            <br />
            <label for="password">Password</label>
            <input class="form-control" type="password" name="password" value="" size="50" />
            <br />
            <input type="submit" value="Login" class="btn btn-default btn-block" />
          </form>
          {% else %}
          <a class="btn btn-primary btn-block" href="{% url 'accounts:logout' %}">Logout <i class="glyphicon glyphicon-log-out"></i></a>
          <a class="btn btn-default btn-block" href="{% url 'hubs:manage' %}">Manage Hubs</a>


          {% endif %}
          {% block side_block %}{% endblock %}
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
         <div>
           {% if messages %}
           <div class="messages">
             {% for message in messages %}
             <div class="alert alert-{% if message.tags %}{{ message.tags }}{% endif %}">
              <button type="button" class="close" data-dismiss="alert">&times;</button>
              {{ message }}
             </div>
             {% endfor %}
           </div>
           {% endif %}
           {% block body_block %}{% endblock %}
         </div>
      </div>
      </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
  </body>
</html>

master/templates/master/index.html
{% extends "master/base.html" %}
{% block body_block %}
{% if user.is_authenticated %}


<h2>Hello {{ user.first_name }}. Welcome to <i>i</i>Riot!</h2>

<ul id="tabs" class="nav nav-tabs" data-tabs="tabs">
  {% for room in user.room_set.all %}
  <li><a href="#{{room.id}}" data-toggle="tab">{{room.name}}</a></li>
  {% endfor %}
  <li><a href="#add" data-toggle="tab"><i class="glyphicon glyphicon-plus"></i></a></li>
</ul>
<div id="my-tab-content" class="tab-content">
  {% for room in user.room_set.all %}
  <div class="tab-pane" id="{{room.id}}">
    <br/>
    <!--
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">Room Presets</h3>
      </div>
      <div class="panel-body">
        No presets.
      </div>
    </div>
    -->
    <div class="row">
      {% for device in room.device_set.all %}
      <div class="col-md-4">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">{{ device.name }}</h3>
          </div>
          <div class="panel-body">
            <div class="btn-group-vertical btn-block" role="group">
              {% for function in device.function_set.all %}
              <a class="btn btn-default" id="function{{function.id}}" onclick="send_function('{{function.id}}','#function{{function.id}}')">{{function.function}}</a>
              {% endfor %}
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
    <div class="btn-group" role="group">
      <div class="btn-group" role="group">
    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Edit
      <span class="caret"></span>
    </button>
    <ul class="dropdown-menu">
      <li><a href="{% url 'hubs:manage' %}">Edit Room Hubs</a></li>
      <li><a href="{% url 'devices:manage' room.id %}">Edit Room Devices</a></li>
      <li><a data-toggle="modal" data-target="#modal{{room.id}}">Edit Name</a></li>
    </ul>
  </div>
      <a class="btn btn-danger" href="{% url 'rooms:remove_room' room.id %}">Remove Room <i class="glyphicon glyphicon-trash"></i></a>
    </div>
  </div>
  {% endfor %}
  <div class="tab-pane" id="add">
    <h3>Add a room</h3>
    <form method="post" action="{% url 'rooms:room' %}">
    {% csrf_token %}

    {% for field in room_form.visible_fields %}
    <div class="form-group">
      {{ field.errors }}
      <label>{{ field.label }}</label>
      {{ field }}
    </div>
    {% endfor %}
    <br/>
  <button type="submit" class="btn btn-default">Add Room</button>
</form>
  </div>
</div>

{% for room in user.room_set.all %}
<div class="modal fade" id="modal{{room.id}}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Edit Name</h4>
      </div>
      <form method="post" action="{% url 'rooms:edit_room_name' %}">
      {% csrf_token %}
      <div class="modal-body">
        <input type="text" class="form-control" name="q" value="{{room.name}}"/>
        <input type="hidden" name="room_id" value="{{ room.id }}">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Save changes</button>
      </div>
      </form>
    </div>
  </div>
</div>
{% endfor %}


{% else %}
<div class="jumbotron">
  <h1>Welcome to <i>i</i>Riot!</h1>
  <p>The internet of things. simplified.</p>
  <p><a class="btn btn-primary btn-lg" href="{% url 'accounts:register' %}" role="button">Register Now</a></p>
</div>
<p class="lead">In traditional IoT systems, every device communicates via a WiFi connection, placing a significant load on your local network and creating an unnecessarily large cyber attack surface. Our solution is different.</p>
<h3>Old Dogs, New Tricks.</h3>
<p>Why should creating a “smart home” involve buying brand-new, “smart” devices? Many TVs, light switches, fans, AC units, and more already contain IR sensors. By placing one of our hubs on the ceiling of every room in your home, you will be able to control all of these devices from one, simple web app.</p>
<h3>Security is Key.</h3>
<p>Amazon provides our project with a robust, secure Internet of Things backbone. Loaded with air-tight features, you should never have to worry about unwanted intruders in your network.</p>
{% endif %}


{% endblock %}
{% block head_block %}
<script type="text/javascript">
    $(document).ready(function ($) {
        $('#tabs').tab();
    });
    function send_function(function_id, button_id){
      var url = "devices/"+function_id+"/send_function"
      $.ajax({
        url: url,
        cache: false,
        success: function(html){
          if (html == "t") {
            $(button_id).css("background-color", "green").animate({
              backgroundColor: "#95a5a6",
            }, 1000 );
          } else {
            $(button_id).css("background-color", "red").animate({
              backgroundColor: "#95a5a6",
            }, 1000 );
          }
        }
      });
    }
</script>
<script src="https://code.jquery.com/color/jquery.color-2.1.2.min.js"></script>
{% endblock %}